title: Lightspeed Web Browser
description: Modern web browser for PowerPC Mac based on Mozilla technologies.
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/RetroSoftwareRepository/lightspeed
